/* Generated by the Nim Compiler v2.3.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI738197518 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078609 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078616 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI251658263 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI251658253 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI251658255 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI251658257 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI251658261 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI251658261 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI251658261.node = NNI251658261;
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
NTI251658261.base = NTI33555176;
var NNI251658257 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI251658257.node = NNI251658257;
NTI251658257.base = NTI33555176;
var NNI251658255 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI251658255.node = NNI251658255;
var NNI251658253 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI251658253.node = NNI251658253;
NTI251658253.base = NTI33555176;
NTI251658255.base = NTI251658253;
var NNI251658263 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI251658263.node = NNI251658263;
NTI251658263.base = NTI33555176;
var NNI973078616 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI973078609, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI973078616.node = NNI973078616;
var NNI738197518 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI738197518.node = NNI738197518;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557334 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_u0__system(ti_p2))) {
      result_33557334 = src_p1;
      }
      else {
        result_33557334 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557334 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557334 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557334 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557334 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557334, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557334 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557334 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557334 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557334[i] = nimCopy(result_33557334[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557334 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557334 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557334[i] = nimCopy(result_33557334[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557334 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557334 = src_p1;
      break;
    }

  return result_33557334;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function isObj(obj_p0, subclass_p1) {
  var result_33557435 = false;

  BeforeRet: {
    var x_33557436 = obj_p0;
    if ((x_33557436 == subclass_p1)) {
    result_33557435 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557436 == subclass_p1))) break Label2;
          if ((x_33557436 == null)) {
          result_33557435 = false;
          break BeforeRet;
          }
          
          x_33557436 = x_33557436.base;
        }
    };
    result_33557435 = true;
    break BeforeRet;
  };

  return result_33557435;

}

function toJSStr(s_p0) {
  var result_33556923 = null;

    var res_33556989 = newSeq_u9__system((s_p0).length);
    var i_33556990 = 0;
    var j_33556991 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556990 < (s_p0).length)) break Label2;
          var c_33556992 = s_p0[i_33556990];
          if ((c_33556992 < 128)) {
          res_33556989[j_33556991] = String.fromCharCode(c_33556992);
          i_33556990 += 1;
          }
          else {
            var helper_33557014 = newSeq_u9__system(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557015 = c_33556992.toString(16);
                  if ((((code_33557015) == null ? 0 : (code_33557015).length) == 1)) {
                  helper_33557014.push("%0");;
                  }
                  else {
                  helper_33557014.push("%");;
                  }
                  
                  helper_33557014.push(code_33557015);;
                  i_33556990 += 1;
                  if ((((s_p0).length <= i_33556990) || (s_p0[i_33556990] < 128))) {
                  break Label3;
                  }
                  
                  c_33556992 = s_p0[i_33556990];
                }
            };
++excHandler;
            try {
            res_33556989[j_33556991] = decodeURIComponent(helper_33557014.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556989[j_33556991] = helper_33557014.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556991 += 1;
        }
    };
    if (res_33556989.length < j_33556991) { for (var i = res_33556989.length ; i < j_33556991 ; ++i) res_33556989.push(null); }
               else { res_33556989.length = j_33556991; };
    result_33556923 = res_33556989.join("");

  return result_33556923;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557369 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557369 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557369;

}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557374 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557374 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557374;

}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557161 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557161 = Temporary1;
    break BeforeRet;
  };

  return result_33557161;

}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557157 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }
    
    result_33557157 = Temporary1;
    break BeforeRet;
  };

  return result_33557157;

}

function addChar(x_p0, c_p1) {
    x_p0.push(c_p1);

  
}
var objectID_1191182514 = [0];

function setTheme(theme_p0) {
    document.documentElement.setAttribute("data-theme", theme_p0);
    window.localStorage.setItem("theme", theme_p0);

  
}

function isFatPointer_u0__system(ti_p0) {
  var result_33557316 = false;

  BeforeRet: {
    result_33557316 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557316;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars_u4__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544521 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544521 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544527 = 0;
      var i_587203580 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_587203580 < n_p3)) break Label4;
            iHEX60gensym4_335544527 = i_587203580;
            result_p0[result_p0_Idx][(old_335544521 + iHEX60gensym4_335544527)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544527));
            i_587203580 += 1;
          }
      };
    };

  
}

function addChars_u3__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addChars_u4__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt_u1__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addChars_u3__stdZprivateZdigitsutils(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt_u2__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addInt_u1__stdZprivateZdigitsutils(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24_u1__systemZdollars(xHEX60gensym0_p0) {
  var result_402653200 = [[]];

    result_402653200[0] = nimCopy(null, [], NTI33554449);
    addInt_u2__stdZprivateZdigitsutils(result_402653200, 0, xHEX60gensym0_p0);

  return result_402653200[0];

}

function add_u4__system(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq_u9__system(len_p0) {
  var result_33556968 = [];

    result_33556968 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556968[i] = null; }
  return result_33556968;

}

function isNimException_u0__system() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556467 = null;

    if (isNimException_u0__system()) {
    result_33556467 = lastJSError;
    }
    

  return result_33556467;

}

function raiseDefect() {
    if (isNimException_u0__system()) {
    var e_33556672 = getCurrentException();
    if (isObj(e_33556672.m_type, NTI33555176)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556672);
    }
    
    throw e_33556672;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556666 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556666[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556666[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556666[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556666[0], [32,91]);;
    add_u4__system(buf_33556666, 0, e_p0.name);
    nimAddStrStr(buf_33556666[0], [93,10]);;
    var cbuf_33556667 = toJSStr(buf_33556666[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556667);
  }
  else {
    throw cbuf_33556667;
  }
  

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24_u1__systemZdollars(i_p0),[32,110,111,116,32,105,110,32],HEX24_u1__systemZdollars(a_p1),[32,46,46,32],HEX24_u1__systemZdollars(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI251658261, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_u2__stdZassertions(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI251658257, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_u0__stdZassertions(msg_p0) {
    sysFatal_u2__stdZassertions(msg_p0);

  
}

function failedAssertImpl_u0__stdZassertions(msg_p0) {
    raiseAssert_u0__stdZassertions(msg_p0);

  
}

function onDOMLoaded(e_p0) {
            var Temporary4;

function HEX3Aanonymous_u0__dochack(event_p0) {
    event_p0.target.parentNode.style.display = "none";
    event_p0.target.parentNode.nextSibling.style.display = "inline";

  
}

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_587202621 = null;
      var colontmp__587203571 = [];
      colontmp__587203571 = document.getElementsByClassName("pragmadots");
      var i_587203573 = 0;
      var L_587203574 = (colontmp__587203571).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203573 < L_587203574)) break Label3;
            pragmaDots_587202621 = colontmp__587203571[chckIndx(i_587203573, 0, (colontmp__587203571).length - 1)];
            Temporary4 = HEX3Aanonymous_u0__dochack.bind(null); Temporary4.ClP_0 = HEX3Aanonymous_u0__dochack; Temporary4.ClE_0 = null;
            pragmaDots_587202621.onclick = Temporary4;
            i_587203573 += 1;
            if (!(((colontmp__587203571).length == L_587203574))) {
            failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI251658255, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function isWhitespace_u1__dochack(x_p0) {
  var result_587202907 = false;

    result_587202907 = (((x_p0.nodeName == "#text") && !/\S/.test(x_p0.textContent)) || (x_p0.nodeName == "#comment"));

  return result_587202907;

}

function toToc_u0__dochack(x_p0, father_p1) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_p0.nodeName == "UL")) {
    var f_587202915 = {heading: null, kids: [], sortId: (father_p1.kids).length, doSort: false};
    var i_587202916 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_587202916 < x_p0.childNodes.length)) break Label2;
          var nxt_587202917 = addInt(i_587202916, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_587202917 < x_p0.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_u1__dochack(x_p0.childNodes[nxt_587202917]);                }              if (!Temporary5) break Label4;
                nxt_587202917 = addInt(nxt_587202917, 1);
              }
          };
            if (!(nxt_587202917 < x_p0.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_p0.childNodes[i_587202916].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_p0.childNodes[i_587202916].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_p0.childNodes[nxt_587202917].nodeName == "UL");            }          if (Temporary6) {
          var e_587202923 = {heading: x_p0.childNodes[i_587202916].childNodes[0], kids: [], sortId: (f_587202915.kids).length, doSort: false};
          var it_587202924 = x_p0.childNodes[nxt_587202917];
          Label9: {
            var j_587202929 = 0;
            var colontmp__587203588 = 0;
            colontmp__587203588 = it_587202924.childNodes.length;
            var i_587203589 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_587203589 < colontmp__587203588)) break Label11;
                  j_587202929 = i_587203589;
                  toToc_u0__dochack(it_587202924.childNodes[j_587202929], e_587202923);
                  i_587203589 = addInt(i_587203589, 1);
                }
            };
          };
          f_587202915.kids.push(e_587202923);;
          i_587202916 = addInt(nxt_587202917, 1);
          }
          else {
            toToc_u0__dochack(x_p0.childNodes[i_587202916], f_587202915);
            i_587202916 = addInt(i_587202916, 1);
          }
          
        }
    };
    father_p1.kids.push(f_587202915);;
    }
    else {
    if (isWhitespace_u1__dochack(x_p0)) {
    }
    else {
    if ((x_p0.nodeName == "LI")) {
    var idx_587202943 = [];
    Label12: {
      var i_587202948 = 0;
      var colontmp__587203592 = 0;
      colontmp__587203592 = x_p0.childNodes.length;
      var i_587203593 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_587203593 < colontmp__587203592)) break Label14;
            i_587202948 = i_587203593;
            if (!(isWhitespace_u1__dochack(x_p0.childNodes[i_587202948]))) {
            idx_587202943.push(i_587202948);;
            }
            
            i_587203593 = addInt(i_587203593, 1);
          }
      };
    };
      if (!((idx_587202943).length == 2)) Temporary15 = false; else {        Temporary15 = (x_p0.childNodes[idx_587202943[chckIndx(1, 0, (idx_587202943).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_587202957 = {heading: x_p0.childNodes[idx_587202943[chckIndx(0, 0, (idx_587202943).length - 1)]], kids: [], sortId: (father_p1.kids).length, doSort: false};
    var it_587202958 = x_p0.childNodes[idx_587202943[chckIndx(1, 0, (idx_587202943).length - 1)]];
    Label16: {
      var j_587202963 = 0;
      var colontmp__587203596 = 0;
      colontmp__587203596 = it_587202958.childNodes.length;
      var i_587203597 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_587203597 < colontmp__587203596)) break Label18;
            j_587202963 = i_587203597;
            toToc_u0__dochack(it_587202958.childNodes[j_587202963], e_587202957);
            i_587203597 = addInt(i_587203597, 1);
          }
      };
    };
    father_p1.kids.push(e_587202957);;
    }
    else {
      Label19: {
        var i_587202968 = 0;
        var colontmp__587203600 = 0;
        colontmp__587203600 = x_p0.childNodes.length;
        var i_587203601 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_587203601 < colontmp__587203600)) break Label21;
              i_587202968 = i_587203601;
              toToc_u0__dochack(x_p0.childNodes[i_587202968], father_p1);
              i_587203601 = addInt(i_587203601, 1);
            }
        };
      };
    }
    
    }
    else {
    father_p1.kids.push({heading: x_p0, kids: [], sortId: (father_p1.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems_u1__dochack(x_p0, heading_p1, items_p2, items_p2_Idx) {
  BeforeRet: {
    if ((x_p0 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_p0.heading == null)) && (x_p0.heading.textContent == heading_p1))) {
    Label1: {
      var i_587202756 = 0;
      var colontmp__587203604 = 0;
      colontmp__587203604 = (x_p0.kids).length;
      var i_587203605 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203605 < colontmp__587203604)) break Label3;
            i_587202756 = i_587203605;
            items_p2[items_p2_Idx].push(x_p0.kids[chckIndx(i_587202756, 0, (x_p0.kids).length - 1)].heading);;
            i_587203605 = addInt(i_587203605, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_587202772 = null;
        var i_587203609 = 0;
        var L_587203610 = (x_p0.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_587203609 < L_587203610)) break Label6;
              k_587202772 = x_p0.kids[chckIndx(i_587203609, 0, (x_p0.kids).length - 1)];
              extractItems_u1__dochack(k_587202772, heading_p1, items_p2, items_p2_Idx);
              i_587203609 += 1;
              if (!(((x_p0.kids).length == L_587203610))) {
              failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree_u0__dochack(tag_p0, kids_p1) {
  var result_587202674 = null;

    result_587202674 = document.createElement(tag_p0);
    Label1: {
      var k_587202688 = null;
      var i_587203622 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203622 < (kids_p1).length)) break Label3;
            k_587202688 = kids_p1[chckIndx(i_587203622, 0, (kids_p1).length - 1)];
            result_587202674.appendChild(k_587202688);
            i_587203622 += 1;
          }
      };
    };

  return result_587202674;

}

function text_u0__dochack(s_p0) {
  var result_587202698 = null;

    result_587202698 = document.createTextNode(s_p0);

  return result_587202698;

}

function uncovered_u0__dochack(x_p0) {
    var Temporary1;

  var result_587203047 = null;

  BeforeRet: {
    if ((((x_p0.kids).length == 0) && !((x_p0.heading == null)))) {
    if (!(x_p0.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_p0;
    }
    else {
    Temporary1 = null;
    }
    
    result_587203047 = Temporary1;
    break BeforeRet;
    }
    
    result_587203047 = {heading: x_p0.heading, kids: [], sortId: x_p0.sortId, doSort: x_p0.doSort};
    Label2: {
      var k_587203048 = null;
      var i_587203629 = 0;
      var L_587203630 = (x_p0.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_587203629 < L_587203630)) break Label4;
            k_587203048 = x_p0.kids[chckIndx(i_587203629, 0, (x_p0.kids).length - 1)];
            var y_587203049 = uncovered_u0__dochack(k_587203048);
            if (!((y_587203049 == null))) {
            result_587203047.kids.push(y_587203049);;
            }
            
            i_587203629 += 1;
            if (!(((x_p0.kids).length == L_587203630))) {
            failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_587203047.kids).length == 0)) {
    result_587203047 = null;
    }
    
  };

  return result_587203047;

}

function mergeTocs_u0__dochack(orig_p0, news_p1) {
  var result_587203053 = null;

    result_587203053 = uncovered_u0__dochack(orig_p0);
    if ((result_587203053 == null)) {
    result_587203053 = news_p1;
    }
    else {
      Label1: {
        var i_587203058 = 0;
        var colontmp__587203625 = 0;
        colontmp__587203625 = (news_p1.kids).length;
        var i_587203626 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_587203626 < colontmp__587203625)) break Label3;
              i_587203058 = i_587203626;
              result_587203053.kids.push(news_p1.kids[chckIndx(i_587203058, 0, (news_p1.kids).length - 1)]);;
              i_587203626 = addInt(i_587203626, 1);
            }
        };
      };
    }
    

  return result_587203053;

}

function buildToc_u0__dochack(orig_p0, types_p1, procs_p2) {
  var result_587203063 = null;

    var newStuff_587203064 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_587203065 = null;
      var i_587203617 = 0;
      var L_587203618 = (types_p1).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203617 < L_587203618)) break Label3;
            t_587203065 = types_p1[chckIndx(i_587203617, 0, (types_p1).length - 1)];
            var c_587203066 = {heading: t_587203065.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_587203065.__karaxMarker__ = true;
            Label4: {
              var p_587203067 = null;
              var i_587203614 = 0;
              var L_587203615 = (procs_p2).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_587203614 < L_587203615)) break Label6;
                    p_587203067 = procs_p2[chckIndx(i_587203614, 0, (procs_p2).length - 1)];
                    if (!(p_587203067.hasOwnProperty('__karaxMarker__'))) {
                    var xx_587203068 = p_587203067.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_587203068).length == 1) && (xx_587203068[chckIndx(0, 0, (xx_587203068).length - 1)].textContent == t_587203065.textContent))) {
                    var q_587203073 = tree_u0__dochack("A", [text_u0__dochack(p_587203067.title)]);
                    q_587203073.setAttribute("href", p_587203067.getAttribute("href"));
                    c_587203066.kids.push({heading: q_587203073, kids: [], sortId: 0, doSort: false});;
                    p_587203067.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_587203614 += 1;
                    if (!(((procs_p2).length == L_587203615))) {
                    failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_587203064.kids.push(c_587203066);;
            i_587203617 += 1;
            if (!(((types_p1).length == L_587203618))) {
            failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_587203063 = mergeTocs_u0__dochack(orig_p0, newStuff_587203064);

  return result_587203063;

}

function add_u0__dochack(parent_p0, kid_p1) {
    if (((parent_p0.nodeName == "TR") && ((kid_p1.nodeName == "TD") || (kid_p1.nodeName == "TH")))) {
    var k_587202692 = document.createElement("TD");
    k_587202692.appendChild(kid_p1);
    parent_p0.appendChild(k_587202692);
    }
    else {
    parent_p0.appendChild(kid_p1);
    }
    

  
}

function setClass_u0__dochack(e_p0, value_p1) {
    e_p0.setAttribute("class", value_p1);

  
}

function toHtml_u0__dochack(x_p0, isRoot_p1) {
    var Temporary1;

function HEX3Aanonymous_u1__dochack(a_p0, b_p1) {
  var result_587202813 = 0;

  BeforeRet: {
    if ((!((a_p0.heading == null)) && !((b_p1.heading == null)))) {
    var x_587202814 = a_p0.heading.textContent;
    var y_587202815 = b_p1.heading.textContent;
    if ((x_587202814 < y_587202815)) {
    result_587202813 = (-1);
    break BeforeRet;
    }
    
    if ((y_587202815 < x_587202814)) {
    result_587202813 = 1;
    break BeforeRet;
    }
    
    result_587202813 = 0;
    break BeforeRet;
    }
    else {
      result_587202813 = subInt(a_p0.sortId, b_p1.sortId);
      break BeforeRet;
    }
    
  };

  return result_587202813;

}

  var result_587202808 = null;

  BeforeRet: {
    if ((x_p0 == null)) {
    result_587202808 = null;
    break BeforeRet;
    }
    
    if (((x_p0.kids).length == 0)) {
    if ((x_p0.heading == null)) {
    result_587202808 = null;
    break BeforeRet;
    }
    
    result_587202808 = x_p0.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_587202808 = tree_u0__dochack("DIV", []);
    if ((!((x_p0.heading == null)) && !(x_p0.heading.hasOwnProperty('__karaxMarker__')))) {
    add_u0__dochack(result_587202808, x_p0.heading.cloneNode(true));
    }
    
    var ul_587202809 = tree_u0__dochack("UL", []);
    if (isRoot_p1) {
    setClass_u0__dochack(ul_587202809, "simple simple-toc");
    }
    else {
    setClass_u0__dochack(ul_587202809, "simple");
    }
    
    if (x_p0.doSort) {
    Temporary1 = HEX3Aanonymous_u1__dochack.bind(null); Temporary1.ClP_0 = HEX3Aanonymous_u1__dochack; Temporary1.ClE_0 = null;
    x_p0.kids.sort(Temporary1);
    }
    
    Label2: {
      var k_587202824 = null;
      var i_587203633 = 0;
      var L_587203634 = (x_p0.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_587203633 < L_587203634)) break Label4;
            k_587202824 = x_p0.kids[chckIndx(i_587203633, 0, (x_p0.kids).length - 1)];
            var y_587202825 = toHtml_u0__dochack(k_587202824, false);
            if (!((y_587202825 == null))) {
            add_u0__dochack(ul_587202809, tree_u0__dochack("LI", [y_587202825]));
            }
            
            i_587203633 += 1;
            if (!(((x_p0.kids).length == L_587203634))) {
            failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_587202809.childNodes.length == 0))) {
    add_u0__dochack(result_587202808, ul_587202809);
    }
    
    if ((result_587202808.childNodes.length == 0)) {
    result_587202808 = null;
    }
    
  };

  return result_587202808;

}

function replaceById_u0__dochack(id_p0, newTree_p1) {
    var x_587202702 = document.getElementById(id_p0);
    x_587202702.parentNode.replaceChild(newTree_p1, x_587202702);
    newTree_p1.id = id_p0;

  
}

function togglevis_u0__dochack(d_p0) {
    if ((d_p0.style.display == "none")) {
    d_p0.style.display = "inline";
    }
    else {
      d_p0.style.display = "none";
    }
    

  
}

function groupBy(value_p0) {
    var toc_587203095 = document.getElementById("toc-list");
    if ((alternative_587203090[0] == null)) {
    var tt_587203099 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc_u0__dochack(toc_587203095, tt_587203099);
    tt_587203099 = tt_587203099.kids[chckIndx(0, 0, (tt_587203099.kids).length - 1)];
    var types_587203104 = [[]];
    var procs_587203105 = [[]];
    extractItems_u1__dochack(tt_587203099, "Types", types_587203104, 0);
    extractItems_u1__dochack(tt_587203099, "Procs", procs_587203105, 0);
    extractItems_u1__dochack(tt_587203099, "Converters", procs_587203105, 0);
    extractItems_u1__dochack(tt_587203099, "Methods", procs_587203105, 0);
    extractItems_u1__dochack(tt_587203099, "Templates", procs_587203105, 0);
    extractItems_u1__dochack(tt_587203099, "Macros", procs_587203105, 0);
    extractItems_u1__dochack(tt_587203099, "Iterators", procs_587203105, 0);
    var ntoc_587203106 = buildToc_u0__dochack(tt_587203099, types_587203104[0], procs_587203105[0]);
    var x_587203107 = toHtml_u0__dochack(ntoc_587203106, true);
    alternative_587203090[0] = tree_u0__dochack("DIV", [x_587203107]);
    }
    
    if ((value_p0 == "type")) {
    replaceById_u0__dochack("tocRoot", alternative_587203090[0]);
    }
    else {
    replaceById_u0__dochack("tocRoot", tree_u0__dochack("DIV", []));
    }
    
    togglevis_u0__dochack(document.getElementById("toc-list"));

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI251658263, name: null, trace: [], up: null}, "RangeDefect");

  
}

function HEX5BHEX5D_u1__pureZstrutils(s_p0, x_p1) {
  var result_754976007 = [];

    var a_754976009 = x_p1.a;
    var L_754976011 = addInt(subInt(subInt((s_p0).length, x_p1.b), a_754976009), 1);
    result_754976007 = nimCopy(null, mnewString(chckRange(L_754976011, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_754976016 = 0;
      var i_587203643 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203643 < L_754976011)) break Label3;
            i_754976016 = i_587203643;
            result_754976007[chckIndx(i_754976016, 0, (result_754976007).length - 1)] = s_p0[chckIndx(addInt(i_754976016, a_754976009), 0, (s_p0).length - 1)];
            i_587203643 = addInt(i_587203643, 1);
          }
      };
    };

  return result_754976007;

}

function HEX2EHEX2E_u0__stdZenumutils(a_p0, b_p1) {
  var result_973078640 = ({a: 0, b: 0});

    result_973078640 = nimCopy(result_973078640, {a: a_p0, b: b_p1}, NTI973078616);

  return result_973078640;

}
async function loadIndex_u0__dochack() {
  var result_587203299 = null;

  BeforeRet: {
    var indexURL_587203305 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_587203331 = HEX5BHEX5D_u1__pureZstrutils(cstrToNimstr(indexURL_587203305), HEX2EHEX2E_u0__stdZenumutils(0, 14));
    var resp_587203343 = (await (await fetch(indexURL_587203305)).text());
    var indexElem_587203344 = document.createElement("div");
    indexElem_587203344.innerHTML = resp_587203343;
    Label1: {
      var href_587203360 = null;
      var colontmp__587203637 = [];
      colontmp__587203637 = indexElem_587203344.getElementsByClassName("reference");
      var i_587203639 = 0;
      var L_587203640 = (colontmp__587203637).length;
      Label2: {
          Label3: while (true) {
          if (!(i_587203639 < L_587203640)) break Label3;
            href_587203360 = colontmp__587203637[chckIndx(i_587203639, 0, (colontmp__587203637).length - 1)];
            href_587203360.setAttribute("href", toJSStr((rootURL_587203331).concat(cstrToNimstr(href_587203360.getAttribute("href")))));
            db_587203124[0].push(href_587203360);;
            contents_587203125[0].push(href_587203360.getAttribute("data-doc-search-tag"));;
            i_587203639 += 1;
            if (!(((colontmp__587203637).length == L_587203640))) {
            failedAssertImpl_u0__stdZassertions(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_587203299 = undefined;
    break BeforeRet;
  };

  return result_587203299;

}

function then_u0__dochack(future_p0, onSuccess_p1, onReject_p2) {
  var result_587203454 = null;

  BeforeRet: {
    var ret_587203464 = null;
    ret_587203464 = future_p0.then(onSuccess_p1, onReject_p2);
    result_587203454 = ret_587203464;
    break BeforeRet;
  };

  return result_587203454;

}

function nsuToLowerAsciiChar(c_p0) {
  var result_754974795 = 0;

    if ((ConstSet2[c_p0] != undefined)) {
    result_754974795 = (c_p0 ^ 32);
    }
    else {
      result_754974795 = c_p0;
    }
    

  return result_754974795;

}

function fuzzyMatch_u0__fuzzysearch(pattern_p0, str_p1) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_738197525 = {Field0: 0, Field1: false};

    var scoreState_738197526 = (-100);
    var headerMatched_738197527 = false;
    var unmatchedLeadingCharCount_738197528 = 0;
    var consecutiveMatchCount_738197529 = 0;
    var strIndex_738197530 = 0;
    var patIndex_738197531 = 0;
    var score_738197532 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_738197530 < ((str_p1) == null ? 0 : (str_p1).length)) && (patIndex_738197531 < ((pattern_p0) == null ? 0 : (pattern_p0).length)))) break Label2;
          Label3: {
            var patternChar_738197535 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(patIndex_738197531, 0, (pattern_p0).length - 1)));
            var strChar_738197536 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1)));
            if ((ConstSet3[patternChar_738197535] != undefined)) {
            patIndex_738197531 = addInt(patIndex_738197531, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_738197536] != undefined)) {
            strIndex_738197530 = addInt(strIndex_738197530, 1);
            break Label3;
            }
            
            if ((!(headerMatched_738197527) && (strChar_738197536 == 58))) {
            headerMatched_738197527 = true;
            scoreState_738197526 = (-100);
            score_738197532 = chckRange(Number(BigInt(Math.trunc(Math.floor((0.5 * score_738197532))))), (-2147483648), 2147483647);
            patIndex_738197531 = 0;
            strIndex_738197530 = addInt(strIndex_738197530, 1);
            break Label3;
            }
            
            if ((strChar_738197536 == patternChar_738197535)) {
            switch (scoreState_738197526) {
            case (-100):
            case 20:
              scoreState_738197526 = 10;
              break;
            case 0:
              scoreState_738197526 = 5;
              score_738197532 = addInt(score_738197532, scoreState_738197526);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_738197529 = addInt(consecutiveMatchCount_738197529, 1);
              scoreState_738197526 = 5;
              score_738197532 = addInt(score_738197532, mulInt(5, consecutiveMatchCount_738197529));
              if ((scoreState_738197526 == 10)) {
              score_738197532 = addInt(score_738197532, 10);
              }
              
              var onBoundary_738197582 = (patIndex_738197531 == ((pattern_p0) == null ? -1 : (pattern_p0).length - 1));
              if ((!(onBoundary_738197582) && (strIndex_738197530 < ((str_p1) == null ? -1 : (str_p1).length - 1)))) {
              var nextPatternChar_738197583 = nsuToLowerAsciiChar(pattern_p0.charCodeAt(chckIndx(addInt(patIndex_738197531, 1), 0, (pattern_p0).length - 1)));
              var nextStrChar_738197584 = nsuToLowerAsciiChar(str_p1.charCodeAt(chckIndx(addInt(strIndex_738197530, 1), 0, (str_p1).length - 1)));
              if (!!((ConstSet5[nextStrChar_738197584] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_738197584 == nextPatternChar_738197583));              }              onBoundary_738197582 = Temporary4;
              }
              
              if (onBoundary_738197582) {
              scoreState_738197526 = 20;
              score_738197532 = addInt(score_738197532, scoreState_738197526);
              }
              
              break;
            case (-1):
            case (-3):
              if (!((ConstSet6[str_p1.charCodeAt(chckIndx(subInt(strIndex_738197530, 1), 0, (str_p1).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_p1.charCodeAt(chckIndx(subInt(strIndex_738197530, 1), 0, (str_p1).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_738197605 = Temporary5;
              if (isLeadingChar_738197605) {
              scoreState_738197526 = 10;
              }
              else {
                scoreState_738197526 = 0;
                score_738197532 = addInt(score_738197532, scoreState_738197526);
              }
              
              break;
            }
            patIndex_738197531 = addInt(patIndex_738197531, 1);
            }
            else {
              switch (scoreState_738197526) {
              case (-100):
                scoreState_738197526 = (-3);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                break;
              case 5:
                scoreState_738197526 = (-1);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                consecutiveMatchCount_738197529 = 0;
                break;
              case (-3):
                if ((unmatchedLeadingCharCount_738197528 < 3)) {
                scoreState_738197526 = (-3);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                }
                
                unmatchedLeadingCharCount_738197528 = addInt(unmatchedLeadingCharCount_738197528, 1);
                break;
              default: 
                scoreState_738197526 = (-1);
                score_738197532 = addInt(score_738197532, scoreState_738197526);
                break;
              }
            }
            
            strIndex_738197530 = addInt(strIndex_738197530, 1);
          };
        }
    };
      if (!(patIndex_738197531 == ((pattern_p0) == null ? 0 : (pattern_p0).length))) Temporary7 = false; else {        if ((strIndex_738197530 == ((str_p1) == null ? 0 : (str_p1).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_p1.charCodeAt(chckIndx(strIndex_738197530, 0, (str_p1).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_738197532 = addInt(score_738197532, 10);
    }
    
    var colontmp__587203656 = nimMax(0, score_738197532);
    var colontmp__587203657 = (0 < score_738197532);
    result_738197525 = nimCopy(result_738197525, {Field0: colontmp__587203656, Field1: colontmp__587203657}, NTI738197518);

  return result_738197525;

}

function escapeCString_u0__dochack(x_p0, x_p0_Idx) {
    var s_587203128 = [];
    Label1: {
      var c_587203129 = 0;
      var iHEX60gensym14_587203660 = 0;
      var nHEX60gensym14_587203661 = ((x_p0[x_p0_Idx]) == null ? 0 : (x_p0[x_p0_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym14_587203660 < nHEX60gensym14_587203661)) break Label3;
            c_587203129 = x_p0[x_p0_Idx].charCodeAt(chckIndx(iHEX60gensym14_587203660, 0, (x_p0[x_p0_Idx]).length - 1));
            switch (c_587203129) {
            case 60:
              nimAddStrStr(s_587203128, [38,108,116,59]);;
              break;
            case 62:
              nimAddStrStr(s_587203128, [38,103,116,59]);;
              break;
            default: 
              addChar(s_587203128, c_587203129);;
              break;
            }
            iHEX60gensym14_587203660 += 1;
          }
      };
    };
    x_p0[x_p0_Idx] = toJSStr(s_587203128);

  
}

function dosearch_u0__dochack(value_p0) {
    var Temporary5;

function HEX3Aanonymous_u2__dochack(a_p0, b_p1) {
  var result_587203165 = 0;

    result_587203165 = subInt(b_p1["Field1"], a_p0["Field1"]);

  return result_587203165;

}

  var result_587203132 = null;

  BeforeRet: {
    if (((db_587203124[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_587203133 = tree_u0__dochack("UL", []);
    result_587203132 = tree_u0__dochack("DIV", []);
    setClass_u0__dochack(result_587203132, "search_results");
    var matches_587203138 = [];
    Label1: {
      var i_587203143 = 0;
      var colontmp__587203647 = 0;
      colontmp__587203647 = (db_587203124[0]).length;
      var i_587203648 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_587203648 < colontmp__587203647)) break Label3;
            i_587203143 = i_587203648;
            Label4: {
              var c_587203144 = contents_587203125[0][chckIndx(i_587203143, 0, (contents_587203125[0]).length - 1)];
              if (((c_587203144 == "Examples") || (c_587203144 == "PEG construction"))) {
              break Label4;
              }
              
              var tmpTuple_587203145 = fuzzyMatch_u0__fuzzysearch(value_p0, c_587203144);
              var score_587203146 = tmpTuple_587203145["Field0"];
              var matched_587203147 = tmpTuple_587203145["Field1"];
              if (matched_587203147) {
              matches_587203138.push({Field0: db_587203124[0][chckIndx(i_587203143, 0, (db_587203124[0]).length - 1)], Field1: score_587203146});;
              }
              
            };
            i_587203648 = addInt(i_587203648, 1);
          }
      };
    };
    Temporary5 = HEX3Aanonymous_u2__dochack.bind(null); Temporary5.ClP_0 = HEX3Aanonymous_u2__dochack; Temporary5.ClE_0 = null;
    matches_587203138.sort(Temporary5);
    Label6: {
      var i_587203182 = 0;
      var colontmp__587203651 = 0;
      colontmp__587203651 = nimMin((matches_587203138).length, 29);
      var i_587203652 = 0;
      Label7: {
          Label8: while (true) {
          if (!(i_587203652 < colontmp__587203651)) break Label8;
            i_587203182 = i_587203652;
            matches_587203138[chckIndx(i_587203182, 0, (matches_587203138).length - 1)]["Field0"].innerHTML = matches_587203138[chckIndx(i_587203182, 0, (matches_587203138).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString_u0__dochack(matches_587203138[chckIndx(i_587203182, 0, (matches_587203138).length - 1)]["Field0"], "innerHTML");
            add_u0__dochack(ul_587203133, tree_u0__dochack("LI", [matches_587203138[chckIndx(i_587203182, 0, (matches_587203138).length - 1)]["Field0"]]));
            i_587203652 = addInt(i_587203652, 1);
          }
      };
    };
    if ((ul_587203133.childNodes.length == 0)) {
    add_u0__dochack(result_587203132, tree_u0__dochack("B", [text_u0__dochack("no search results")]));
    }
    else {
      add_u0__dochack(result_587203132, tree_u0__dochack("B", [text_u0__dochack("search results")]));
      add_u0__dochack(result_587203132, ul_587203133);
    }
    
  };

  return result_587203132;

}

function hideSearch_u0__dochack() {
    if (!((oldtoc_587203433[0] == null))) {
    replaceById_u0__dochack("tocRoot", oldtoc_587203433[0]);
    }
    

  
}

function runSearch_u0__dochack() {
    var elem_587203439 = document.getElementById("searchInput");
    var value_587203440 = elem_587203439.value;
    if (!((value_587203440 == ""))) {
    if ((oldtoc_587203433[0] == null)) {
    oldtoc_587203433[0] = document.getElementById("tocRoot");
    }
    
    var results_587203441 = dosearch_u0__dochack(value_587203440);
    replaceById_u0__dochack("tocRoot", results_587203441);
    }
    else {
    hideSearch_u0__dochack();
    }
    

  
}

function search() {
    var Temporary1;

    if ((loadIndexFut_587203436[0] == null)) {
    loadIndexFut_587203436[0] = loadIndex_u0__dochack();
    (then_u0__dochack(loadIndexFut_587203436[0], runSearch_u0__dochack, null));
    }
    
    if (!((timer_587203434[0] == null))) {
    clearTimeout(timer_587203434[0]);
    }
    
    Temporary1 = runSearch_u0__dochack.bind(null); Temporary1.ClP_0 = runSearch_u0__dochack; Temporary1.ClE_0 = null;
    timer_587203434[0] = setTimeout(Temporary1, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre:not(.line-nums)")

      allPreTags.forEach((e) => {

          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")

          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML

          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '')
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"

          div.appendChild(preTag)
          div.appendChild(button)

          e.outerHTML = div.outerHTML

      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })

    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var Temporary2;

function HEX3Aanonymous_u4__dochack(e_p0) {
    if ((e_p0.key == "/")) {
    e_p0.preventDefault();
    var searchElem_587203518 = document.getElementById("searchInput");
    searchElem_587203518.focus();
    searchElem_587203518.parentElement.scrollIntoView();
    runSearch_u0__dochack();
    }
    

  
}
var Temporary3;

function HEX3Aanonymous_u5__dochack(e_p0) {
    hideSearch_u0__dochack();

  
}
var Temporary4;
var t_587202599 = window.localStorage.getItem("theme");
if ((t_587202599 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_587202599;
}

setTheme(Temporary1);
var alternative_587203090 = [null];
var db_587203124 = [[]];
var contents_587203125 = [[]];
var oldtoc_587203433 = [null];
var timer_587203434 = [null];
var loadIndexFut_587203436 = [null];
Temporary2 = HEX3Aanonymous_u4__dochack.bind(null); Temporary2.ClP_0 = HEX3Aanonymous_u4__dochack; Temporary2.ClE_0 = null;
window.addEventListener("keypress", Temporary2, false);
Temporary3 = HEX3Aanonymous_u5__dochack.bind(null); Temporary3.ClP_0 = HEX3Aanonymous_u5__dochack; Temporary3.ClE_0 = null;
window.addEventListener("hashchange", Temporary3, false);
copyToClipboard();
Temporary4 = onDOMLoaded.bind(null); Temporary4.ClP_0 = onDOMLoaded; Temporary4.ClE_0 = null;
window.addEventListener("DOMContentLoaded", Temporary4, false);
