name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y hipcc nvidia-cuda-toolkit
    - run: nimble test -y
    - run: nimble test --gc:orc -y

# TODO setup cpu builds
# TODO setup gpu builds
# TODO setup cpu tests
