name: Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # container: 
    #   image: ubuntu:24.04

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        sudo wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.1 jammy main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
        echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
        sudo apt-get update
        sudo apt-get install -y hipcc nvidia-cuda-toolkit
    
    - name: Run Tests
      - run: nimble test -y
      - run: nimble test --gc:orc -y

    - name: Build Examples
      - run: nim cpp examples/vector_sum_cpu.nim
      - run: nim cpp examples/vector_sum.nim

# TODO setup cpu builds
# TODO setup gpu builds
# TODO setup cpu tests
